python3 train.py --encoding multi --learner linear --style ucb --nu 1 --lamdba 1 --inv diag --dataset mushroom 
python3 train.py --encoding multi --learner linear --style ts --nu 0.1 --lamdba 1 --inv diag --dataset mushroom
python3 train.py --encoding multi --learner linear --style ucb --nu 1 --lamdba 1 --inv diag --dataset shuttle
python3 train.py --encoding multi --learner linear --style ts --nu 0.1 --lamdba 1 --inv diag --dataset shuttle
python3 train.py --encoding multi --learner linear --style ucb --nu 1 --lamdba 1 --inv diag --dataset adult
python3 train.py --encoding multi --learner linear --style ts --nu 0.1 --lamdba 1 --inv diag --dataset adult
python3 train.py --encoding multi --learner linear --style ucb --nu 1 --lamdba 1 --inv diag --dataset MagicTelescope
python3 train.py --encoding multi --learner linear --style ts --nu 1 --lamdba 1 --inv diag --dataset MagicTelescope
python3 train.py --encoding multi --learner linear --style ucb --nu 1 --lamdba 1 --inv diag --dataset covertype
python3 train.py --encoding multi --learner linear --style ts --nu 1 --lamdba 1 --inv diag --dataset covertype
python3 train.py --encoding multi --learner linear --style ucb --nu 10 --lamdba 1 --inv diag --dataset letter
python3 train.py --encoding multi --learner linear --style ts --nu 0.1 --lamdba 1 --inv diag --dataset letter